//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", ConfigurationName="ProductService.ProductService_v1Soap")]
    public interface ProductService_v1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.vensafe.com/zervio/ProductService_v1/UseExtendedExportData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> UseExtendedExportDataAsync(bool extendedExport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.vensafe.com/zervio/ProductService_v1/UpdateEanByEan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.UpdateEanByEanResponse1> UpdateEanByEanAsync(ProductService.UpdateEanByEanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.vensafe.com/zervio/ProductService_v1/GetProductsInStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.GetProductsInStockResponse> GetProductsInStockAsync(ProductService.GetProductsInStockRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class UpdateEanByEanRequestBody
    {
        
        private string oldEanField;
        
        private string newEanField;
        
        private bool replaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string oldEan
        {
            get
            {
                return this.oldEanField;
            }
            set
            {
                this.oldEanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string newEan
        {
            get
            {
                return this.newEanField;
            }
            set
            {
                this.newEanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool replace
        {
            get
            {
                return this.replaceField;
            }
            set
            {
                this.replaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class EanDetailType
    {
        
        private string eANField;
        
        private string detailMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EAN
        {
            get
            {
                return this.eANField;
            }
            set
            {
                this.eANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DetailMessage
        {
            get
            {
                return this.detailMessageField;
            }
            set
            {
                this.detailMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class PriceUpdateType
    {
        
        private string eANField;
        
        private double priceField;
        
        private CurrencyType currencyField;
        
        private bool currencyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EAN
        {
            get
            {
                return this.eANField;
            }
            set
            {
                this.eANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public CurrencyType Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencySpecified
        {
            get
            {
                return this.currencyFieldSpecified;
            }
            set
            {
                this.currencyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public enum CurrencyType
    {
        
        /// <remarks/>
        CHF,
        
        /// <remarks/>
        DKK,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        RUB,
        
        /// <remarks/>
        SEK,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        unspecified,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class BrandType
    {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class GroupType
    {
        
        private int idField;
        
        private string nameField;
        
        private int ageLimitField;
        
        private bool isAnonymousField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int AgeLimit
        {
            get
            {
                return this.ageLimitField;
            }
            set
            {
                this.ageLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool IsAnonymous
        {
            get
            {
                return this.isAnonymousField;
            }
            set
            {
                this.isAnonymousField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class ProductType
    {
        
        private string productCodeField;
        
        private string productNameField;
        
        private string descriptionField;
        
        private string contentCountField;
        
        private string eANField;
        
        private double priceField;
        
        private bool priceFieldSpecified;
        
        private CurrencyType currencyField;
        
        private bool currencyFieldSpecified;
        
        private GroupType groupField;
        
        private BrandType brandField;
        
        private int stockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ProductCode
        {
            get
            {
                return this.productCodeField;
            }
            set
            {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ContentCount
        {
            get
            {
                return this.contentCountField;
            }
            set
            {
                this.contentCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EAN
        {
            get
            {
                return this.eANField;
            }
            set
            {
                this.eANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified
        {
            get
            {
                return this.priceFieldSpecified;
            }
            set
            {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public CurrencyType Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencySpecified
        {
            get
            {
                return this.currencyFieldSpecified;
            }
            set
            {
                this.currencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public GroupType Group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public BrandType Brand
        {
            get
            {
                return this.brandField;
            }
            set
            {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int Stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                this.stockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class StockData
    {
        
        private string eANField;
        
        private string productCodeField;
        
        private int quantityInStockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EAN
        {
            get
            {
                return this.eANField;
            }
            set
            {
                this.eANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ProductCode
        {
            get
            {
                return this.productCodeField;
            }
            set
            {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int QuantityInStock
        {
            get
            {
                return this.quantityInStockField;
            }
            set
            {
                this.quantityInStockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class ResultType
    {
        
        private ResultCodeType resultCodeField;
        
        private string detailMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultCodeType ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DetailMessage
        {
            get
            {
                return this.detailMessageField;
            }
            set
            {
                this.detailMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public enum ResultCodeType
    {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        SERVER_ERROR,
        
        /// <remarks/>
        SERVICE_DISABLED,
        
        /// <remarks/>
        INVALID_DATA,
        
        /// <remarks/>
        IGNORED_DATA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class UpdateEanByEanResponse
    {
        
        private ResultType resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultType Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEanByEanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.UpdateEanByEanRequestBody UpdateEanByEan;
        
        public UpdateEanByEanRequest()
        {
        }
        
        public UpdateEanByEanRequest(ProductService.UpdateEanByEanRequestBody UpdateEanByEan)
        {
            this.UpdateEanByEan = UpdateEanByEan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEanByEanResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.UpdateEanByEanResponse UpdateEanByEanResponse;
        
        public UpdateEanByEanResponse1()
        {
        }
        
        public UpdateEanByEanResponse1(ProductService.UpdateEanByEanResponse UpdateEanByEanResponse)
        {
            this.UpdateEanByEanResponse = UpdateEanByEanResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductsInStock", WrapperNamespace="http://webservices.vensafe.com/zervio/ProductService_v1", IsWrapped=true)]
    public partial class GetProductsInStockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] eanCodes;
        
        public GetProductsInStockRequest()
        {
        }
        
        public GetProductsInStockRequest(string[] eanCodes)
        {
            this.eanCodes = eanCodes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductsInStockResponse", WrapperNamespace="http://webservices.vensafe.com/zervio/ProductService_v1", IsWrapped=true)]
    public partial class GetProductsInStockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ProductService.StockData[] GetProductsInStockResult;
        
        public GetProductsInStockResponse()
        {
        }
        
        public GetProductsInStockResponse(ProductService.StockData[] GetProductsInStockResult)
        {
            this.GetProductsInStockResult = GetProductsInStockResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ProductService_v1SoapChannel : ProductService.ProductService_v1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ProductService_v1SoapClient : System.ServiceModel.ClientBase<ProductService.ProductService_v1Soap>, ProductService.ProductService_v1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductService_v1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductService_v1SoapClient.GetBindingForEndpoint(endpointConfiguration), ProductService_v1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductService_v1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductService_v1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductService_v1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductService_v1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductService_v1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> UseExtendedExportDataAsync(bool extendedExport)
        {
            return base.Channel.UseExtendedExportDataAsync(extendedExport);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductService.UpdateEanByEanResponse1> ProductService.ProductService_v1Soap.UpdateEanByEanAsync(ProductService.UpdateEanByEanRequest request)
        {
            return base.Channel.UpdateEanByEanAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductService.UpdateEanByEanResponse1> UpdateEanByEanAsync(ProductService.UpdateEanByEanRequestBody UpdateEanByEan)
        {
            ProductService.UpdateEanByEanRequest inValue = new ProductService.UpdateEanByEanRequest();
            inValue.UpdateEanByEan = UpdateEanByEan;
            return ((ProductService.ProductService_v1Soap)(this)).UpdateEanByEanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductService.GetProductsInStockResponse> ProductService.ProductService_v1Soap.GetProductsInStockAsync(ProductService.GetProductsInStockRequest request)
        {
            return base.Channel.GetProductsInStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductService.GetProductsInStockResponse> GetProductsInStockAsync(string[] eanCodes)
        {
            ProductService.GetProductsInStockRequest inValue = new ProductService.GetProductsInStockRequest();
            inValue.eanCodes = eanCodes;
            return ((ProductService.ProductService_v1Soap)(this)).GetProductsInStockAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductService_v1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ProductService_v1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductService_v1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8084/webservicesnew/productservice_v1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ProductService_v1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8084/webservicesnew/productservice_v1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ProductService_v1Soap,
            
            ProductService_v1Soap12,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", ConfigurationName="ProductService.ProductService_v1_Soap")]
    public interface ProductService_v1_Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.vensafe.com/zervio/ProductService_v1/GetProductsInUse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.GetProductsInUseResponse1> GetProductsInUseAsync(ProductService.GetProductsInUseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.vensafe.com/zervio/ProductService_v1/ExportProductsInUse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.ExportProductsInUseResponse1> ExportProductsInUseAsync(ProductService.ExportProductsInUseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.vensafe.com/zervio/ProductService_v1/SubscribeProductExport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.SubscribeProductExportResponse1> SubscribeProductExportAsync(ProductService.SubscribeProductExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.vensafe.com/zervio/ProductService_v1/UnsubscribeProductExport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.UnsubscribeProductExportResponse1> UnsubscribeProductExportAsync(ProductService.UnsubscribeProductExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.vensafe.com/zervio/ProductService_v1/SetProductPricesByEan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.SetProductPricesByEanResponse1> SetProductPricesByEanAsync(ProductService.SetProductPricesByEanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.vensafe.com/zervio/ProductService_v1/AddLogEntry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.AddLogEntryResponse1> AddLogEntryAsync(ProductService.AddLogEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.vensafe.com/zervio/ProductService_v1/GetProductByVensafeCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.GetProductByVensafeCodeResponse1> GetProductByVensafeCodeAsync(ProductService.GetProductByVensafeCodeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class GetProductsInUse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class GetProductsInUseResponse
    {
        
        private ResultType resultField;
        
        private ProductType[] productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultType Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Products", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductType[] Products
        {
            get
            {
                return this.productsField;
            }
            set
            {
                this.productsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsInUseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.GetProductsInUse GetProductsInUse;
        
        public GetProductsInUseRequest()
        {
        }
        
        public GetProductsInUseRequest(ProductService.GetProductsInUse GetProductsInUse)
        {
            this.GetProductsInUse = GetProductsInUse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsInUseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.GetProductsInUseResponse GetProductsInUseResponse;
        
        public GetProductsInUseResponse1()
        {
        }
        
        public GetProductsInUseResponse1(ProductService.GetProductsInUseResponse GetProductsInUseResponse)
        {
            this.GetProductsInUseResponse = GetProductsInUseResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class ExportProductsInUse
    {
        
        private string productExportUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string ProductExportUrl
        {
            get
            {
                return this.productExportUrlField;
            }
            set
            {
                this.productExportUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class ExportProductsInUseResponse
    {
        
        private ResultType resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultType Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportProductsInUseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.ExportProductsInUse ExportProductsInUse;
        
        public ExportProductsInUseRequest()
        {
        }
        
        public ExportProductsInUseRequest(ProductService.ExportProductsInUse ExportProductsInUse)
        {
            this.ExportProductsInUse = ExportProductsInUse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportProductsInUseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.ExportProductsInUseResponse ExportProductsInUseResponse;
        
        public ExportProductsInUseResponse1()
        {
        }
        
        public ExportProductsInUseResponse1(ProductService.ExportProductsInUseResponse ExportProductsInUseResponse)
        {
            this.ExportProductsInUseResponse = ExportProductsInUseResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class SubscribeProductExport
    {
        
        private string productExportUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string ProductExportUrl
        {
            get
            {
                return this.productExportUrlField;
            }
            set
            {
                this.productExportUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class SubscribeProductExportResponse
    {
        
        private ResultType resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultType Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubscribeProductExportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.SubscribeProductExport SubscribeProductExport;
        
        public SubscribeProductExportRequest()
        {
        }
        
        public SubscribeProductExportRequest(ProductService.SubscribeProductExport SubscribeProductExport)
        {
            this.SubscribeProductExport = SubscribeProductExport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubscribeProductExportResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.SubscribeProductExportResponse SubscribeProductExportResponse;
        
        public SubscribeProductExportResponse1()
        {
        }
        
        public SubscribeProductExportResponse1(ProductService.SubscribeProductExportResponse SubscribeProductExportResponse)
        {
            this.SubscribeProductExportResponse = SubscribeProductExportResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class UnsubscribeProductExport
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class UnsubscribeProductExportResponse
    {
        
        private ResultType resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultType Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnsubscribeProductExportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.UnsubscribeProductExport UnsubscribeProductExport;
        
        public UnsubscribeProductExportRequest()
        {
        }
        
        public UnsubscribeProductExportRequest(ProductService.UnsubscribeProductExport UnsubscribeProductExport)
        {
            this.UnsubscribeProductExport = UnsubscribeProductExport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnsubscribeProductExportResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.UnsubscribeProductExportResponse UnsubscribeProductExportResponse;
        
        public UnsubscribeProductExportResponse1()
        {
        }
        
        public UnsubscribeProductExportResponse1(ProductService.UnsubscribeProductExportResponse UnsubscribeProductExportResponse)
        {
            this.UnsubscribeProductExportResponse = UnsubscribeProductExportResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class SetProductPricesByEanResponse
    {
        
        private ResultType resultField;
        
        private EanDetailType[] ignoredDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultType Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IgnoredData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public EanDetailType[] IgnoredData
        {
            get
            {
                return this.ignoredDataField;
            }
            set
            {
                this.ignoredDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetProductPricesByEanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PriceUpdates", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProductService.PriceUpdateType[] SetProductPricesByEan;
        
        public SetProductPricesByEanRequest()
        {
        }
        
        public SetProductPricesByEanRequest(ProductService.PriceUpdateType[] SetProductPricesByEan)
        {
            this.SetProductPricesByEan = SetProductPricesByEan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetProductPricesByEanResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.SetProductPricesByEanResponse SetProductPricesByEanResponse;
        
        public SetProductPricesByEanResponse1()
        {
        }
        
        public SetProductPricesByEanResponse1(ProductService.SetProductPricesByEanResponse SetProductPricesByEanResponse)
        {
            this.SetProductPricesByEanResponse = SetProductPricesByEanResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class AddLogEntry
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class AddLogEntryResponse
    {
        
        private ResultType resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultType Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLogEntryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.AddLogEntry AddLogEntry;
        
        public AddLogEntryRequest()
        {
        }
        
        public AddLogEntryRequest(ProductService.AddLogEntry AddLogEntry)
        {
            this.AddLogEntry = AddLogEntry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLogEntryResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.AddLogEntryResponse AddLogEntryResponse;
        
        public AddLogEntryResponse1()
        {
        }
        
        public AddLogEntryResponse1(ProductService.AddLogEntryResponse AddLogEntryResponse)
        {
            this.AddLogEntryResponse = AddLogEntryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class GetProductByVensafeCode
    {
        
        private string vensafeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VensafeCode
        {
            get
            {
                return this.vensafeCodeField;
            }
            set
            {
                this.vensafeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.vensafe.com/zervio/ProductService_v1")]
    public partial class GetProductByVensafeCodeResponse
    {
        
        private ResultType resultField;
        
        private ProductType productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultType Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductType Products
        {
            get
            {
                return this.productsField;
            }
            set
            {
                this.productsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductByVensafeCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.GetProductByVensafeCode GetProductByVensafeCode;
        
        public GetProductByVensafeCodeRequest()
        {
        }
        
        public GetProductByVensafeCodeRequest(ProductService.GetProductByVensafeCode GetProductByVensafeCode)
        {
            this.GetProductByVensafeCode = GetProductByVensafeCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductByVensafeCodeResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.vensafe.com/zervio/ProductService_v1", Order=0)]
        public ProductService.GetProductByVensafeCodeResponse GetProductByVensafeCodeResponse;
        
        public GetProductByVensafeCodeResponse1()
        {
        }
        
        public GetProductByVensafeCodeResponse1(ProductService.GetProductByVensafeCodeResponse GetProductByVensafeCodeResponse)
        {
            this.GetProductByVensafeCodeResponse = GetProductByVensafeCodeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ProductService_v1_SoapChannel : ProductService.ProductService_v1_Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ProductService_v1_SoapClient : System.ServiceModel.ClientBase<ProductService.ProductService_v1_Soap>, ProductService.ProductService_v1_Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductService_v1_SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductService_v1_SoapClient.GetBindingForEndpoint(endpointConfiguration), ProductService_v1_SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductService_v1_SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductService_v1_SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductService_v1_SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductService_v1_SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductService_v1_SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductService.GetProductsInUseResponse1> ProductService.ProductService_v1_Soap.GetProductsInUseAsync(ProductService.GetProductsInUseRequest request)
        {
            return base.Channel.GetProductsInUseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductService.GetProductsInUseResponse1> GetProductsInUseAsync(ProductService.GetProductsInUse GetProductsInUse)
        {
            ProductService.GetProductsInUseRequest inValue = new ProductService.GetProductsInUseRequest();
            inValue.GetProductsInUse = GetProductsInUse;
            return ((ProductService.ProductService_v1_Soap)(this)).GetProductsInUseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductService.ExportProductsInUseResponse1> ProductService.ProductService_v1_Soap.ExportProductsInUseAsync(ProductService.ExportProductsInUseRequest request)
        {
            return base.Channel.ExportProductsInUseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductService.ExportProductsInUseResponse1> ExportProductsInUseAsync(ProductService.ExportProductsInUse ExportProductsInUse)
        {
            ProductService.ExportProductsInUseRequest inValue = new ProductService.ExportProductsInUseRequest();
            inValue.ExportProductsInUse = ExportProductsInUse;
            return ((ProductService.ProductService_v1_Soap)(this)).ExportProductsInUseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductService.SubscribeProductExportResponse1> ProductService.ProductService_v1_Soap.SubscribeProductExportAsync(ProductService.SubscribeProductExportRequest request)
        {
            return base.Channel.SubscribeProductExportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductService.SubscribeProductExportResponse1> SubscribeProductExportAsync(ProductService.SubscribeProductExport SubscribeProductExport)
        {
            ProductService.SubscribeProductExportRequest inValue = new ProductService.SubscribeProductExportRequest();
            inValue.SubscribeProductExport = SubscribeProductExport;
            return ((ProductService.ProductService_v1_Soap)(this)).SubscribeProductExportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductService.UnsubscribeProductExportResponse1> ProductService.ProductService_v1_Soap.UnsubscribeProductExportAsync(ProductService.UnsubscribeProductExportRequest request)
        {
            return base.Channel.UnsubscribeProductExportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductService.UnsubscribeProductExportResponse1> UnsubscribeProductExportAsync(ProductService.UnsubscribeProductExport UnsubscribeProductExport)
        {
            ProductService.UnsubscribeProductExportRequest inValue = new ProductService.UnsubscribeProductExportRequest();
            inValue.UnsubscribeProductExport = UnsubscribeProductExport;
            return ((ProductService.ProductService_v1_Soap)(this)).UnsubscribeProductExportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductService.SetProductPricesByEanResponse1> ProductService.ProductService_v1_Soap.SetProductPricesByEanAsync(ProductService.SetProductPricesByEanRequest request)
        {
            return base.Channel.SetProductPricesByEanAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductService.SetProductPricesByEanResponse1> SetProductPricesByEanAsync(ProductService.PriceUpdateType[] SetProductPricesByEan)
        {
            ProductService.SetProductPricesByEanRequest inValue = new ProductService.SetProductPricesByEanRequest();
            inValue.SetProductPricesByEan = SetProductPricesByEan;
            return ((ProductService.ProductService_v1_Soap)(this)).SetProductPricesByEanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductService.AddLogEntryResponse1> ProductService.ProductService_v1_Soap.AddLogEntryAsync(ProductService.AddLogEntryRequest request)
        {
            return base.Channel.AddLogEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductService.AddLogEntryResponse1> AddLogEntryAsync(ProductService.AddLogEntry AddLogEntry)
        {
            ProductService.AddLogEntryRequest inValue = new ProductService.AddLogEntryRequest();
            inValue.AddLogEntry = AddLogEntry;
            return ((ProductService.ProductService_v1_Soap)(this)).AddLogEntryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductService.GetProductByVensafeCodeResponse1> ProductService.ProductService_v1_Soap.GetProductByVensafeCodeAsync(ProductService.GetProductByVensafeCodeRequest request)
        {
            return base.Channel.GetProductByVensafeCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductService.GetProductByVensafeCodeResponse1> GetProductByVensafeCodeAsync(ProductService.GetProductByVensafeCode GetProductByVensafeCode)
        {
            ProductService.GetProductByVensafeCodeRequest inValue = new ProductService.GetProductByVensafeCodeRequest();
            inValue.GetProductByVensafeCode = GetProductByVensafeCode;
            return ((ProductService.ProductService_v1_Soap)(this)).GetProductByVensafeCodeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductService_v1_Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ProductService_v1_Soap1))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductService_v1_Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8084/webservicesnew/productservice_v1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ProductService_v1_Soap1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8084/webservicesnew/productservice_v1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ProductService_v1_Soap,
            
            ProductService_v1_Soap1,
        }
    }
}
