//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApi
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VensafeMessage", Namespace="http://services.vensafe.com/SalesApi")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesApi.Ticket))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesApi.Product[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesApi.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesApi.BaseProduct))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesApi.ProductInventory))]
    public partial class VensafeMessage : object
    {
        
        private int MessageNoField;
        
        private string MessageTextField;
        
        private string MessageInfoField;
        
        private bool IsSuccessField;
        
        private object ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MessageNo
        {
            get
            {
                return this.MessageNoField;
            }
            set
            {
                this.MessageNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageText
        {
            get
            {
                return this.MessageTextField;
            }
            set
            {
                this.MessageTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageInfo
        {
            get
            {
                return this.MessageInfoField;
            }
            set
            {
                this.MessageInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool IsSuccess
        {
            get
            {
                return this.IsSuccessField;
            }
            set
            {
                this.IsSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public object Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ticket", Namespace="http://services.vensafe.com/SalesApi")]
    public partial class Ticket : object
    {
        
        private int TicketNoField;
        
        private string TicketNameField;
        
        private string CallerIdField;
        
        private int CallerTransNoField;
        
        private short TicketStatusField;
        
        private string TicketStatusNameField;
        
        private string AssociatedCodeField;
        
        private string PodBarcodeField;
        
        private string VensafePrefixCodeField;
        
        private System.DateTime CreatedTimeField;
        
        private System.DateTime UpdatedTimeField;
        
        private System.DateTime ExpireTimeField;
        
        private System.Nullable<System.DateTime> ConfirmedTimeField;
        
        private System.Nullable<System.DateTime> CancelledTimeField;
        
        private System.Nullable<System.DateTime> DeliveredTimeField;
        
        private short TotalRequestedQuantityField;
        
        private short TotalDeliveredQuantityField;
        
        private SalesApi.Product[] ProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TicketNo
        {
            get
            {
                return this.TicketNoField;
            }
            set
            {
                this.TicketNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TicketName
        {
            get
            {
                return this.TicketNameField;
            }
            set
            {
                this.TicketNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CallerId
        {
            get
            {
                return this.CallerIdField;
            }
            set
            {
                this.CallerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CallerTransNo
        {
            get
            {
                return this.CallerTransNoField;
            }
            set
            {
                this.CallerTransNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public short TicketStatus
        {
            get
            {
                return this.TicketStatusField;
            }
            set
            {
                this.TicketStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TicketStatusName
        {
            get
            {
                return this.TicketStatusNameField;
            }
            set
            {
                this.TicketStatusNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AssociatedCode
        {
            get
            {
                return this.AssociatedCodeField;
            }
            set
            {
                this.AssociatedCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PodBarcode
        {
            get
            {
                return this.PodBarcodeField;
            }
            set
            {
                this.PodBarcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string VensafePrefixCode
        {
            get
            {
                return this.VensafePrefixCodeField;
            }
            set
            {
                this.VensafePrefixCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime CreatedTime
        {
            get
            {
                return this.CreatedTimeField;
            }
            set
            {
                this.CreatedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime UpdatedTime
        {
            get
            {
                return this.UpdatedTimeField;
            }
            set
            {
                this.UpdatedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime ExpireTime
        {
            get
            {
                return this.ExpireTimeField;
            }
            set
            {
                this.ExpireTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<System.DateTime> ConfirmedTime
        {
            get
            {
                return this.ConfirmedTimeField;
            }
            set
            {
                this.ConfirmedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<System.DateTime> CancelledTime
        {
            get
            {
                return this.CancelledTimeField;
            }
            set
            {
                this.CancelledTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<System.DateTime> DeliveredTime
        {
            get
            {
                return this.DeliveredTimeField;
            }
            set
            {
                this.DeliveredTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public short TotalRequestedQuantity
        {
            get
            {
                return this.TotalRequestedQuantityField;
            }
            set
            {
                this.TotalRequestedQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public short TotalDeliveredQuantity
        {
            get
            {
                return this.TotalDeliveredQuantityField;
            }
            set
            {
                this.TotalDeliveredQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public SalesApi.Product[] Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://services.vensafe.com/SalesApi")]
    public partial class Product : SalesApi.BaseProduct
    {
        
        private short QuantityField;
        
        private short ReservedQuantityField;
        
        private short DeliveredQuantityField;
        
        private short RemainingQuantityField;
        
        private System.DateTime CreatedTimeField;
        
        private System.DateTime UpdatedTimeField;
        
        private short AvailableQuantityField;
        
        private short AvailabilityStatusField;
        
        private string AvailabilityStatusNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short ReservedQuantity
        {
            get
            {
                return this.ReservedQuantityField;
            }
            set
            {
                this.ReservedQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public short DeliveredQuantity
        {
            get
            {
                return this.DeliveredQuantityField;
            }
            set
            {
                this.DeliveredQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public short RemainingQuantity
        {
            get
            {
                return this.RemainingQuantityField;
            }
            set
            {
                this.RemainingQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CreatedTime
        {
            get
            {
                return this.CreatedTimeField;
            }
            set
            {
                this.CreatedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime UpdatedTime
        {
            get
            {
                return this.UpdatedTimeField;
            }
            set
            {
                this.UpdatedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public short AvailableQuantity
        {
            get
            {
                return this.AvailableQuantityField;
            }
            set
            {
                this.AvailableQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public short AvailabilityStatus
        {
            get
            {
                return this.AvailabilityStatusField;
            }
            set
            {
                this.AvailabilityStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AvailabilityStatusName
        {
            get
            {
                return this.AvailabilityStatusNameField;
            }
            set
            {
                this.AvailabilityStatusNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseProduct", Namespace="http://services.vensafe.com/SalesApi")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SalesApi.Product))]
    public partial class BaseProduct : object
    {
        
        private string ProductCodeField;
        
        private string ProductNameField;
        
        private string EanPluField;
        
        private string DescriptionField;
        
        private int BrandNoField;
        
        private string BrandNameField;
        
        private int GroupNoField;
        
        private string GroupNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EanPlu
        {
            get
            {
                return this.EanPluField;
            }
            set
            {
                this.EanPluField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int BrandNo
        {
            get
            {
                return this.BrandNoField;
            }
            set
            {
                this.BrandNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BrandName
        {
            get
            {
                return this.BrandNameField;
            }
            set
            {
                this.BrandNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int GroupNo
        {
            get
            {
                return this.GroupNoField;
            }
            set
            {
                this.GroupNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInventory", Namespace="http://services.vensafe.com/SalesApi")]
    public partial class ProductInventory : object
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.vensafe.com/SalesApi", ConfigurationName="SalesApi.SalesApiSoap")]
    public interface SalesApiSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.vensafe.com/SalesApi/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<SalesApi.PingResponse> PingAsync(SalesApi.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.vensafe.com/SalesApi/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<SalesApi.AddResponse> AddAsync(SalesApi.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.vensafe.com/SalesApi/Confirm", ReplyAction="*")]
        System.Threading.Tasks.Task<SalesApi.ConfirmResponse> ConfirmAsync(SalesApi.ConfirmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.vensafe.com/SalesApi/Cancel", ReplyAction="*")]
        System.Threading.Tasks.Task<SalesApi.CancelResponse> CancelAsync(SalesApi.CancelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.vensafe.com/SalesApi/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<SalesApi.GetProductsResponse> GetProductsAsync(SalesApi.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.vensafe.com/SalesApi/GetTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<SalesApi.GetTicketResponse> GetTicketAsync(SalesApi.GetTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.vensafe.com/SalesApi/PocCreate", ReplyAction="*")]
        System.Threading.Tasks.Task<SalesApi.PocCreateResponse> PocCreateAsync(SalesApi.PocCreateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ping", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.PingRequestBody Body;
        
        public PingRequest()
        {
        }
        
        public PingRequest(SalesApi.PingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PingRequestBody
    {
        
        public PingRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingResponse", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.PingResponseBody Body;
        
        public PingResponse()
        {
        }
        
        public PingResponse(SalesApi.PingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class PingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SalesApi.VensafeMessage PingResult;
        
        public PingResponseBody()
        {
        }
        
        public PingResponseBody(SalesApi.VensafeMessage PingResult)
        {
            this.PingResult = PingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.AddRequestBody Body;
        
        public AddRequest()
        {
        }
        
        public AddRequest(SalesApi.AddRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class AddRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CallerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CallerTransNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VensafeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public short Quantity;
        
        public AddRequestBody()
        {
        }
        
        public AddRequestBody(string CallerId, int CallerTransNo, string VensafeCode, short Quantity)
        {
            this.CallerId = CallerId;
            this.CallerTransNo = CallerTransNo;
            this.VensafeCode = VensafeCode;
            this.Quantity = Quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.AddResponseBody Body;
        
        public AddResponse()
        {
        }
        
        public AddResponse(SalesApi.AddResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class AddResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SalesApi.VensafeMessage AddResult;
        
        public AddResponseBody()
        {
        }
        
        public AddResponseBody(SalesApi.VensafeMessage AddResult)
        {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Confirm", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.ConfirmRequestBody Body;
        
        public ConfirmRequest()
        {
        }
        
        public ConfirmRequest(SalesApi.ConfirmRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class ConfirmRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TicketNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CallerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CallerTransNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AssociatedCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SalesApi.Product[] Products;
        
        public ConfirmRequestBody()
        {
        }
        
        public ConfirmRequestBody(int TicketNo, string CallerId, int CallerTransNo, string AssociatedCode, SalesApi.Product[] Products)
        {
            this.TicketNo = TicketNo;
            this.CallerId = CallerId;
            this.CallerTransNo = CallerTransNo;
            this.AssociatedCode = AssociatedCode;
            this.Products = Products;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmResponse", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.ConfirmResponseBody Body;
        
        public ConfirmResponse()
        {
        }
        
        public ConfirmResponse(SalesApi.ConfirmResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class ConfirmResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SalesApi.VensafeMessage ConfirmResult;
        
        public ConfirmResponseBody()
        {
        }
        
        public ConfirmResponseBody(SalesApi.VensafeMessage ConfirmResult)
        {
            this.ConfirmResult = ConfirmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cancel", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.CancelRequestBody Body;
        
        public CancelRequest()
        {
        }
        
        public CancelRequest(SalesApi.CancelRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class CancelRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TicketNo;
        
        public CancelRequestBody()
        {
        }
        
        public CancelRequestBody(int TicketNo)
        {
            this.TicketNo = TicketNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelResponse", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.CancelResponseBody Body;
        
        public CancelResponse()
        {
        }
        
        public CancelResponse(SalesApi.CancelResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class CancelResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SalesApi.VensafeMessage CancelResult;
        
        public CancelResponseBody()
        {
        }
        
        public CancelResponseBody(SalesApi.VensafeMessage CancelResult)
        {
            this.CancelResult = CancelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.GetProductsRequestBody Body;
        
        public GetProductsRequest()
        {
        }
        
        public GetProductsRequest(SalesApi.GetProductsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class GetProductsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VensafeCode;
        
        public GetProductsRequestBody()
        {
        }
        
        public GetProductsRequestBody(string VensafeCode)
        {
            this.VensafeCode = VensafeCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.GetProductsResponseBody Body;
        
        public GetProductsResponse()
        {
        }
        
        public GetProductsResponse(SalesApi.GetProductsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class GetProductsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SalesApi.VensafeMessage GetProductsResult;
        
        public GetProductsResponseBody()
        {
        }
        
        public GetProductsResponseBody(SalesApi.VensafeMessage GetProductsResult)
        {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicket", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.GetTicketRequestBody Body;
        
        public GetTicketRequest()
        {
        }
        
        public GetTicketRequest(SalesApi.GetTicketRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class GetTicketRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TicketNo;
        
        public GetTicketRequestBody()
        {
        }
        
        public GetTicketRequestBody(int TicketNo)
        {
            this.TicketNo = TicketNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketResponse", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.GetTicketResponseBody Body;
        
        public GetTicketResponse()
        {
        }
        
        public GetTicketResponse(SalesApi.GetTicketResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class GetTicketResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SalesApi.VensafeMessage GetTicketResult;
        
        public GetTicketResponseBody()
        {
        }
        
        public GetTicketResponseBody(SalesApi.VensafeMessage GetTicketResult)
        {
            this.GetTicketResult = GetTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PocCreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PocCreate", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.PocCreateRequestBody Body;
        
        public PocCreateRequest()
        {
        }
        
        public PocCreateRequest(SalesApi.PocCreateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class PocCreateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CallerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SalesApi.Product[] Products;
        
        public PocCreateRequestBody()
        {
        }
        
        public PocCreateRequestBody(string CallerId, SalesApi.Product[] Products)
        {
            this.CallerId = CallerId;
            this.Products = Products;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PocCreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PocCreateResponse", Namespace="http://services.vensafe.com/SalesApi", Order=0)]
        public SalesApi.PocCreateResponseBody Body;
        
        public PocCreateResponse()
        {
        }
        
        public PocCreateResponse(SalesApi.PocCreateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.vensafe.com/SalesApi")]
    public partial class PocCreateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SalesApi.VensafeMessage PocCreateResult;
        
        public PocCreateResponseBody()
        {
        }
        
        public PocCreateResponseBody(SalesApi.VensafeMessage PocCreateResult)
        {
            this.PocCreateResult = PocCreateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SalesApiSoapChannel : SalesApi.SalesApiSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SalesApiSoapClient : System.ServiceModel.ClientBase<SalesApi.SalesApiSoap>, SalesApi.SalesApiSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SalesApiSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SalesApiSoapClient.GetBindingForEndpoint(endpointConfiguration), SalesApiSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesApiSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SalesApiSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesApiSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SalesApiSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalesApi.PingResponse> SalesApi.SalesApiSoap.PingAsync(SalesApi.PingRequest request)
        {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalesApi.PingResponse> PingAsync()
        {
            SalesApi.PingRequest inValue = new SalesApi.PingRequest();
            inValue.Body = new SalesApi.PingRequestBody();
            return ((SalesApi.SalesApiSoap)(this)).PingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalesApi.AddResponse> SalesApi.SalesApiSoap.AddAsync(SalesApi.AddRequest request)
        {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalesApi.AddResponse> AddAsync(string CallerId, int CallerTransNo, string VensafeCode, short Quantity)
        {
            SalesApi.AddRequest inValue = new SalesApi.AddRequest();
            inValue.Body = new SalesApi.AddRequestBody();
            inValue.Body.CallerId = CallerId;
            inValue.Body.CallerTransNo = CallerTransNo;
            inValue.Body.VensafeCode = VensafeCode;
            inValue.Body.Quantity = Quantity;
            return ((SalesApi.SalesApiSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalesApi.ConfirmResponse> SalesApi.SalesApiSoap.ConfirmAsync(SalesApi.ConfirmRequest request)
        {
            return base.Channel.ConfirmAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalesApi.ConfirmResponse> ConfirmAsync(int TicketNo, string CallerId, int CallerTransNo, string AssociatedCode, SalesApi.Product[] Products)
        {
            SalesApi.ConfirmRequest inValue = new SalesApi.ConfirmRequest();
            inValue.Body = new SalesApi.ConfirmRequestBody();
            inValue.Body.TicketNo = TicketNo;
            inValue.Body.CallerId = CallerId;
            inValue.Body.CallerTransNo = CallerTransNo;
            inValue.Body.AssociatedCode = AssociatedCode;
            inValue.Body.Products = Products;
            return ((SalesApi.SalesApiSoap)(this)).ConfirmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalesApi.CancelResponse> SalesApi.SalesApiSoap.CancelAsync(SalesApi.CancelRequest request)
        {
            return base.Channel.CancelAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalesApi.CancelResponse> CancelAsync(int TicketNo)
        {
            SalesApi.CancelRequest inValue = new SalesApi.CancelRequest();
            inValue.Body = new SalesApi.CancelRequestBody();
            inValue.Body.TicketNo = TicketNo;
            return ((SalesApi.SalesApiSoap)(this)).CancelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalesApi.GetProductsResponse> SalesApi.SalesApiSoap.GetProductsAsync(SalesApi.GetProductsRequest request)
        {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalesApi.GetProductsResponse> GetProductsAsync(string VensafeCode)
        {
            SalesApi.GetProductsRequest inValue = new SalesApi.GetProductsRequest();
            inValue.Body = new SalesApi.GetProductsRequestBody();
            inValue.Body.VensafeCode = VensafeCode;
            return ((SalesApi.SalesApiSoap)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalesApi.GetTicketResponse> SalesApi.SalesApiSoap.GetTicketAsync(SalesApi.GetTicketRequest request)
        {
            return base.Channel.GetTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalesApi.GetTicketResponse> GetTicketAsync(int TicketNo)
        {
            SalesApi.GetTicketRequest inValue = new SalesApi.GetTicketRequest();
            inValue.Body = new SalesApi.GetTicketRequestBody();
            inValue.Body.TicketNo = TicketNo;
            return ((SalesApi.SalesApiSoap)(this)).GetTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalesApi.PocCreateResponse> SalesApi.SalesApiSoap.PocCreateAsync(SalesApi.PocCreateRequest request)
        {
            return base.Channel.PocCreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalesApi.PocCreateResponse> PocCreateAsync(string CallerId, SalesApi.Product[] Products)
        {
            SalesApi.PocCreateRequest inValue = new SalesApi.PocCreateRequest();
            inValue.Body = new SalesApi.PocCreateRequestBody();
            inValue.Body.CallerId = CallerId;
            inValue.Body.Products = Products;
            return ((SalesApi.SalesApiSoap)(this)).PocCreateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SalesApiSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SalesApiSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SalesApiSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.1.1.86/WebServices/Api/SalesApi.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SalesApiSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.1.1.86/WebServices/Api/SalesApi.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SalesApiSoap,
            
            SalesApiSoap12,
        }
    }
}
